title: Адвокат Тарчевская Наталья Евгеньевна
description: Оказание квалифицированной юридической помощи с 1994 года.
baseurl: / # the subpath of your site, e.g. /support
url: / # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Адвокат Тарчевская #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Адвокат Тарчевская
header: Чем я могу вам помочь?
subheader: Юридические консультации и документы

# Social Links
twitter_username: ntarchevskaya
facebook_page: n.tarchevskaya
email: advokat@tarchevskaya.ru
instagram_username: n.tarchevskaya

# Navivation
nav_item_one: WhatsApp
nav_item_one_link: https://wa.me/79032399085

nav_item_two: Вконтакте
nav_item_two_link: https://vk.com/n.tarchevskaya

nav_item_three: #
nav_item_three_link: #

nav_button: Напишите мне в Telegram
nav_button_link: https://t.me/tarchevskaya

# More Help
help_one_title: Telegram
help_one_content: Если Вы не нашли то, что искали, свяжитесь со мной через Telegram.
help_one_button: Написать
help_one_link: https://t.me/tarchevskaya

help_two_title: WhatsApp
help_two_content: Вы можете также написать мне в WhatsApp, если Вам требуется консультация.
help_two_button: Написать
help_two_link: https://wa.me/79032399085

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
